[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    golden: Golden Test
    smoke: Smoke test
    unit: Unit test
    e2e: End-to-end test
